// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBInt32Value;
@class GPBStringValue;
@class User;
GPB_ENUM_FWD_DECLARE(GenderType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AccountRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AccountRoot : GPBRootObject
@end

#pragma mark - RegisterUserRequest

typedef GPB_ENUM(RegisterUserRequest_FieldNumber) {
  RegisterUserRequest_FieldNumber_Name = 1,
  RegisterUserRequest_FieldNumber_GenderType = 2,
  RegisterUserRequest_FieldNumber_Age = 3,
  RegisterUserRequest_FieldNumber_Pr = 4,
};

@interface RegisterUserRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) enum GenderType genderType;

@property(nonatomic, readwrite) int32_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pr;

@end

/**
 * Fetches the raw value of a @c RegisterUserRequest's @c genderType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RegisterUserRequest_GenderType_RawValue(RegisterUserRequest *message);
/**
 * Sets the raw value of an @c RegisterUserRequest's @c genderType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRegisterUserRequest_GenderType_RawValue(RegisterUserRequest *message, int32_t value);

#pragma mark - RegisterUserResponse

typedef GPB_ENUM(RegisterUserResponse_FieldNumber) {
  RegisterUserResponse_FieldNumber_ApiToken = 1,
  RegisterUserResponse_FieldNumber_User = 2,
};

@interface RegisterUserResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *apiToken;

@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@end

#pragma mark - UpdateProfileRequest

typedef GPB_ENUM(UpdateProfileRequest_FieldNumber) {
  UpdateProfileRequest_FieldNumber_Name = 1,
  UpdateProfileRequest_FieldNumber_Age = 2,
  UpdateProfileRequest_FieldNumber_Pr = 3,
};

@interface UpdateProfileRequest : GPBMessage

/**
 * google.protobufにすると、nullを設定できる。
 * optional扱いにできる。
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Value *age;
/** Test to see if @c age has been set. */
@property(nonatomic, readwrite) BOOL hasAge;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *pr;
/** Test to see if @c pr has been set. */
@property(nonatomic, readwrite) BOOL hasPr;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
