// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBStringValue;
@class GPBTimestamp;
@class ProfileImage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum GenderType

typedef GPB_ENUM(GenderType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GenderType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  GenderType_Male = 0,
  GenderType_Female = 1,
};

GPBEnumDescriptor *GenderType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GenderType_IsValidValue(int32_t value);

#pragma mark - CommonsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CommonsRoot : GPBRootObject
@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_Id_p = 1,
  User_FieldNumber_Name = 2,
  User_FieldNumber_GenderType = 3,
  User_FieldNumber_Age = 4,
  User_FieldNumber_Pr = 5,
  User_FieldNumber_ProfileImage = 6,
  User_FieldNumber_LastOnlineDatetime = 7,
  User_FieldNumber_Created = 8,
  User_FieldNumber_Modified = 9,
};

@interface User : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) GenderType genderType;

@property(nonatomic, readwrite) int32_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pr;

@property(nonatomic, readwrite, strong, null_resettable) ProfileImage *profileImage;
/** Test to see if @c profileImage has been set. */
@property(nonatomic, readwrite) BOOL hasProfileImage;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *lastOnlineDatetime;
/** Test to see if @c lastOnlineDatetime has been set. */
@property(nonatomic, readwrite) BOOL hasLastOnlineDatetime;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *created;
/** Test to see if @c created has been set. */
@property(nonatomic, readwrite) BOOL hasCreated;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *modified;
/** Test to see if @c modified has been set. */
@property(nonatomic, readwrite) BOOL hasModified;

@end

/**
 * Fetches the raw value of a @c User's @c genderType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t User_GenderType_RawValue(User *message);
/**
 * Sets the raw value of an @c User's @c genderType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUser_GenderType_RawValue(User *message, int32_t value);

#pragma mark - ProfileImage

typedef GPB_ENUM(ProfileImage_FieldNumber) {
  ProfileImage_FieldNumber_ImageOriginalURL = 1,
  ProfileImage_FieldNumber_Image100URL = 2,
  ProfileImage_FieldNumber_Image300URL = 3,
  ProfileImage_FieldNumber_Image600URL = 4,
};

@interface ProfileImage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *imageOriginalURL;
/** Test to see if @c imageOriginalURL has been set. */
@property(nonatomic, readwrite) BOOL hasImageOriginalURL;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *image100URL;
/** Test to see if @c image100URL has been set. */
@property(nonatomic, readwrite) BOOL hasImage100URL;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *image300URL;
/** Test to see if @c image300URL has been set. */
@property(nonatomic, readwrite) BOOL hasImage300URL;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *image600URL;
/** Test to see if @c image600URL has been set. */
@property(nonatomic, readwrite) BOOL hasImage600URL;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
