// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;
@class User;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserRoot : GPBRootObject
@end

#pragma mark - GetUsersRequest

typedef GPB_ENUM(GetUsersRequest_FieldNumber) {
  GetUsersRequest_FieldNumber_Limit = 1,
  GetUsersRequest_FieldNumber_MaxOnlineDatetime = 2,
};

@interface GetUsersRequest : GPBMessage

@property(nonatomic, readwrite) int32_t limit;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *maxOnlineDatetime;
/** Test to see if @c maxOnlineDatetime has been set. */
@property(nonatomic, readwrite) BOOL hasMaxOnlineDatetime;

@end

#pragma mark - GetUsersResponse

typedef GPB_ENUM(GetUsersResponse_FieldNumber) {
  GetUsersResponse_FieldNumber_UsersArray = 1,
};

@interface GetUsersResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<User*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@end

#pragma mark - GetUserRequest

typedef GPB_ENUM(GetUserRequest_FieldNumber) {
  GetUserRequest_FieldNumber_UserId = 1,
};

@interface GetUserRequest : GPBMessage

@property(nonatomic, readwrite) int32_t userId;

@end

#pragma mark - GetUserResponse

typedef GPB_ENUM(GetUserResponse_FieldNumber) {
  GetUserResponse_FieldNumber_User = 1,
};

@interface GetUserResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
